# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 70, 591, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_timer = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(72)
        self.lbl_timer.setFont(font)
        self.lbl_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_timer.setObjectName("lbl_timer")
        self.verticalLayout.addWidget(self.lbl_timer)
        self.btn_start_pause = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_start_pause.setObjectName("btn_start_pause")
        self.verticalLayout.addWidget(self.btn_start_pause)
        self.btn_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout.addWidget(self.btn_reset)
        self.btn_skip = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_skip.setObjectName("btn_skip")
        self.verticalLayout.addWidget(self.btn_skip)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt_new_task = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_new_task.setObjectName("txt_new_task")
        self.horizontalLayout.addWidget(self.txt_new_task)
        self.btn_add_task = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_add_task.setObjectName("btn_add_task")
        self.horizontalLayout.addWidget(self.btn_add_task)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.list_tasks = QtWidgets.QListWidget(self.layoutWidget)
        self.list_tasks.setObjectName("list_tasks")
        self.verticalLayout_2.addWidget(self.list_tasks)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_complete_task = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_complete_task.setObjectName("btn_complete_task")
        self.horizontalLayout_3.addWidget(self.btn_complete_task)
        self.btn_remove_task = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_remove_task.setObjectName("btn_remove_task")
        self.horizontalLayout_3.addWidget(self.btn_remove_task)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_timer.setText(_translate("MainWindow", "25:00"))
        self.btn_start_pause.setText(_translate("MainWindow", "iniciar"))
        self.btn_reset.setText(_translate("MainWindow", "Resetar"))
        self.btn_skip.setText(_translate("MainWindow", "Pular"))
        self.txt_new_task.setPlaceholderText(_translate("MainWindow", "Digite uma nova tarefa aqui...."))
        self.btn_add_task.setText(_translate("MainWindow", "Adicionar Tarefa"))
        self.btn_complete_task.setText(_translate("MainWindow", "Marcar Concluída"))
        self.btn_remove_task.setText(_translate("MainWindow", "Remover Tarefa"))
